# Generated by Django 4.2.1 on 2023-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_kiet_email_profile_email_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='blog_images/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
