# Generated by Django 4.2.1 on 2024-03-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
