# Generated by Django 4.2.1 on 2023-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0013_alter_blogpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=10),
        ),
    ]
