# Generated by Django 4.2.1 on 2023-06-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_remove_blogpost_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='user',
        ),
    ]
