# Generated by Django 4.2.1 on 2023-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_rename_author_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='All', max_length=255),
        ),
    ]
