# Generated by Django 4.2.1 on 2023-06-12 08:40

from django.db import migrations
import magazine.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_blogpost_cover_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=magazine.fields.RTFField(),
        ),
    ]
