# Generated by Django 4.2.1 on 2023-06-23 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
