# Generated by Django 4.2.1 on 2023-06-23 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_alter_blogpost_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
