# Generated by Django 4.2.1 on 2023-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_blogpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
